config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: :show do
    resources :items, only: [:create, :destroy]
  end
  
  get 'about' => 'welcome#about'
  
  get 'welcome' => 'welcome#index'
  
  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :items
         
  def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "https://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js
  
  def new
    @item = Item.new
  end
  
  def create
    @user = current_user
    
    @item = Item.new(item_params)
    @item.user = @user
    @item.save!
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @user = current_user
      @item = Item.new
      @items = Item.where(user_id: @user.id)
    else
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="row">
    <div class="col-md-8">
        <h4>Create a new todo list item:</h4>

        <%= form_for [@user, @item], remote: true do |f| %>
            <div class="form-group">
                <%= f.text_area :name, rows: 2, class: 'form-control', placeholder: "New Task Name/Description" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/items/_item.html.erb
<div class="row">
    <div id="item-<%= item.id %>">    
        <div class="pull-left">
            <%= link_to "", [@user, item], method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
        </div>
        <div id="item-check" class="col-md-4">
            <strong><%= item.name %></strong><br />
            <small class="time-ago"><%= distance_of_time_in_words(Time.now, item.created_at.to_date + 7) %> left to complete this task</small><br />
        </div>
    </div>
</div>

    

app/views/items/create.js.erb
$('.items').append('<%= j (render @item) %>');
$('#flash').html('<div class="alert alert-success"><strong><%= @item.name %></strong> has been added to your todo list.</div>');
blocmetrics.report('new task created');
$('#new_item')[0].reset();

app/views/items/destroy.js.erb
$('#item-<%= @item.id %>').remove();
$('#flash').html('<div class="alert alert-success"><strong><%= @item.name %></strong> has been marked as complete and deleted from your todo list.</div>');
blocmetrics.report('task completed');

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title>Blocitoff</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
    <div class="container">
        <ul class="nav nav-tabs">
            <li><%= link_to "Blocitoff", welcome_path %></li>
            <li><%= link_to "About", about_path %></li>
            <% if current_user %>
                <li><%= link_to "My Todo", authenticated_root_path %></li>
            <% end %>
            
            <div class="pull-right user-info">
                <% if user_signed_in? %>
                   Signed in as: <strong><%= current_user.email %></strong> |
                   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
                   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
                <% end %>
            </div>
        </ul>
        
        <div id="flash">
            <% if flash[:notice] %>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:notice] %>
                </div>
            <% elsif flash[:alert] %>
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:alert] %>
                </div> 
            <% end %>
        </div>

        <%= yield %>
    </div>
 </body>
 </html>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="media">
            <div class="media-left">
                <%= image_tag @user.avatar_url(128), class: 'media-object' %>
            </div>
            <div class="media-body">
                <h2 class="media-heading">Welcome <%= @user.email %>!</h2>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 items">
        <h4>Your Todo List:</h4>
        <%= render(@items) || content_tag(:h4, 'Looks like you got everything done! Go have some fun.') %>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <%= render 'items/form' %>
    </div>
</div>    

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>